services:
  - type: web
    name: todo
    env: docker
    dockerfilePath: JetsuenThinley_02250350_DSO101_A1\Backend\Dockerfile
    envVars:
      - key: DB_HOST
        value: localhost
      - key: PORT
        value: 5000

  - type: web
    name: todo
    env: docker
    dockerfilePath: JetsuenThinley_02250350_DSO101_A1\Frontend\Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: http://localhost:5000